name: Deploy

on:
  release:
    types: [created]
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: sh ${{ secrets.WWW_PATH }}/nodepress/scripts/deploy.sh
